server:
  port: 8080
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://matheus.com.br
security:
  jwt:
    token:
      security-key: 556bmg0507
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projeto-spring-boot-cadastro?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin556
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
springdoc:
  pathsToMath:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true